/*
Pkg
This module was originally written to patch Windows executables generated by the pkg tool so one doesn't have to be stuck with the default node.exe icon. If you have the same use case, simply adapt the example above in your build script, and follow these tips:

Run Resource Hacker only on the output of pkg.
Make sure your resource .ico file has the exact same set of icon sizes (16x16, 32x32, 48x48, 64x64, 128x128) as the node.exe template or else the patched .exe will be corrupt! You can use an online tool like ICO Convert to convert from a PNG.
Make sure the mask type is ICONGROUP, and the mask name is 1.

node-resource-hacker
import hacker from '@erhhung/node-resource-hacker';

async function setIcon() {
  try {
    await hacker({
      action:   'addoverwrite', // required
      open:     'bin\app.exe',  // required
      save:     'bin\app.exe',  // optional (default: .open)
      resource: 'res\app.ico',  // optional
      mask: {                   // optional
        type: 'ICONGROUP',
        name: '1',              // optional
        lang: '',               // optional
      },
    });
  } catch (err) {
    console.error(err);
  }
}

*/
